// This file is auto-generated by @hey-api/openapi-ts

export const AdminResetPasswordSchema = {
    properties: {
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['new_password'],
    title: 'AdminResetPassword'
} as const;

export const ApiTokenCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expires At'
        },
        generate_secret: {
            type: 'boolean',
            title: 'Generate Secret',
            default: false
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ApiTokenCreate'
} as const;

export const ApiTokenPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expires At'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        token_prefix: {
            type: 'string',
            title: 'Token Prefix'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        created_by: {
            type: 'string',
            format: 'uuid',
            title: 'Created By'
        },
        last_used_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Used At'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'token_prefix', 'is_active', 'created_by'],
    title: 'ApiTokenPublic'
} as const;

export const ApiTokenSecretPublicSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Secret'
        },
        token_prefix: {
            type: 'string',
            title: 'Token Prefix'
        }
    },
    type: 'object',
    required: ['token', 'token_prefix'],
    title: 'ApiTokenSecretPublic'
} as const;

export const ApiTokensPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ApiTokenPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ApiTokensPublic'
} as const;

export const Body_data_jobs_create_import_jobSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_data-jobs-create_import_job'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        mfa_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mfa Code'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const BudgetCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        year: {
            type: 'integer',
            maximum: 3000,
            minimum: 1900,
            title: 'Year'
        },
        period: {
            '$ref': '#/components/schemas/BudgetPeriod'
        },
        amount: {
            type: 'number',
            exclusiveMinimum: 0,
            title: 'Amount'
        }
    },
    type: 'object',
    required: ['name', 'year', 'period', 'amount'],
    title: 'BudgetCreate'
} as const;

export const BudgetPeriodSchema = {
    type: 'integer',
    enum: [1, 2, 3],
    title: 'BudgetPeriod'
} as const;

export const BudgetPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        year: {
            type: 'integer',
            maximum: 3000,
            minimum: 1900,
            title: 'Year'
        },
        period: {
            '$ref': '#/components/schemas/BudgetPeriod'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        amount: {
            type: 'number',
            title: 'Amount'
        },
        used_amount: {
            type: 'number',
            title: 'Used Amount',
            default: 0
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'year', 'period', 'id', 'amount', 'owner_id'],
    title: 'BudgetPublic'
} as const;

export const BudgetUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        year: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 3000,
                    minimum: 1900
                },
                {
                    type: 'null'
                }
            ],
            title: 'Year'
        },
        period: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/BudgetPeriod'
                },
                {
                    type: 'null'
                }
            ]
        },
        amount: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Amount'
        }
    },
    type: 'object',
    title: 'BudgetUpdate'
} as const;

export const BudgetsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/BudgetPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'BudgetsPublic'
} as const;

export const CategoriesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CategoryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CategoriesPublic'
} as const;

export const CategoryCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        color: {
            type: 'string',
            maxLength: 20,
            minLength: 4,
            title: 'Color'
        }
    },
    type: 'object',
    required: ['name', 'color'],
    title: 'CategoryCreate'
} as const;

export const CategoryPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        color: {
            type: 'string',
            maxLength: 20,
            minLength: 4,
            title: 'Color'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'color', 'id', 'owner_id'],
    title: 'CategoryPublic'
} as const;

export const CategoryUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        color: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20,
                    minLength: 4
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        }
    },
    type: 'object',
    title: 'CategoryUpdate'
} as const;

export const DashboardBudgetUsageSchema = {
    properties: {
        budget_id: {
            type: 'string',
            format: 'uuid',
            title: 'Budget Id'
        },
        budget_name: {
            type: 'string',
            title: 'Budget Name'
        },
        amount: {
            type: 'number',
            title: 'Amount'
        },
        used_amount: {
            type: 'number',
            title: 'Used Amount'
        }
    },
    type: 'object',
    required: ['budget_id', 'budget_name', 'amount', 'used_amount'],
    title: 'DashboardBudgetUsage'
} as const;

export const DashboardCategoryShareSchema = {
    properties: {
        category_id: {
            type: 'string',
            format: 'uuid',
            title: 'Category Id'
        },
        category_name: {
            type: 'string',
            title: 'Category Name'
        },
        amount: {
            type: 'number',
            title: 'Amount'
        }
    },
    type: 'object',
    required: ['category_id', 'category_name', 'amount'],
    title: 'DashboardCategoryShare'
} as const;

export const DashboardPublicSchema = {
    properties: {
        summary: {
            '$ref': '#/components/schemas/DashboardSummary'
        },
        trends: {
            items: {
                '$ref': '#/components/schemas/DashboardTrendPoint'
            },
            type: 'array',
            title: 'Trends'
        },
        category_shares: {
            items: {
                '$ref': '#/components/schemas/DashboardCategoryShare'
            },
            type: 'array',
            title: 'Category Shares'
        },
        budget_usage: {
            items: {
                '$ref': '#/components/schemas/DashboardBudgetUsage'
            },
            type: 'array',
            title: 'Budget Usage'
        }
    },
    type: 'object',
    required: ['summary', 'trends', 'category_shares', 'budget_usage'],
    title: 'DashboardPublic'
} as const;

export const DashboardSummarySchema = {
    properties: {
        income: {
            type: 'number',
            title: 'Income'
        },
        expense: {
            type: 'number',
            title: 'Expense'
        },
        balance: {
            type: 'number',
            title: 'Balance'
        }
    },
    type: 'object',
    required: ['income', 'expense', 'balance'],
    title: 'DashboardSummary'
} as const;

export const DashboardTrendPointSchema = {
    properties: {
        month: {
            type: 'string',
            title: 'Month'
        },
        income: {
            type: 'number',
            title: 'Income'
        },
        expense: {
            type: 'number',
            title: 'Expense'
        }
    },
    type: 'object',
    required: ['month', 'income', 'expense'],
    title: 'DashboardTrendPoint'
} as const;

export const DataJobPublicSchema = {
    properties: {
        job_type: {
            '$ref': '#/components/schemas/DataJobType'
        },
        status: {
            '$ref': '#/components/schemas/DataJobStatus',
            default: 'PENDING'
        },
        template_version: {
            type: 'string',
            maxLength: 20,
            title: 'Template Version',
            default: 'v1'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_by: {
            type: 'string',
            format: 'uuid',
            title: 'Created By'
        },
        total_rows: {
            type: 'integer',
            title: 'Total Rows'
        },
        success_rows: {
            type: 'integer',
            title: 'Success Rows'
        },
        failed_rows: {
            type: 'integer',
            title: 'Failed Rows'
        },
        skipped_rows: {
            type: 'integer',
            title: 'Skipped Rows'
        },
        progress_percent: {
            type: 'integer',
            title: 'Progress Percent'
        },
        failure_reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Failure Reason'
        },
        started_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Started At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        has_result_file: {
            type: 'boolean',
            title: 'Has Result File',
            default: false
        },
        has_error_file: {
            type: 'boolean',
            title: 'Has Error File',
            default: false
        }
    },
    type: 'object',
    required: ['job_type', 'id', 'created_by', 'total_rows', 'success_rows', 'failed_rows', 'skipped_rows', 'progress_percent'],
    title: 'DataJobPublic'
} as const;

export const DataJobStatusSchema = {
    type: 'string',
    enum: ['PENDING', 'PROCESSING', 'SUCCEEDED', 'PARTIAL_SUCCESS', 'FAILED', 'CANCELLED'],
    title: 'DataJobStatus'
} as const;

export const DataJobTypeSchema = {
    type: 'string',
    enum: ['EXPORT', 'IMPORT'],
    title: 'DataJobType'
} as const;

export const DataJobsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DataJobPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DataJobsPublic'
} as const;

export const EntryStatusSchema = {
    type: 'integer',
    enum: [1, 2, 3],
    title: 'EntryStatus'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HandlerUserOptionSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        login_name: {
            type: 'string',
            title: 'Login Name'
        },
        display_name: {
            type: 'string',
            title: 'Display Name'
        }
    },
    type: 'object',
    required: ['id', 'login_name', 'display_name'],
    title: 'HandlerUserOption'
} as const;

export const HandlerUsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/HandlerUserOption'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'HandlerUsersPublic'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const LoginRequestSchema = {
    properties: {
        login_name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Login Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 1,
            title: 'Password'
        },
        mfa_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 6,
                    minLength: 6
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mfa Code'
        }
    },
    type: 'object',
    required: ['login_name', 'password'],
    title: 'LoginRequest'
} as const;

export const MFAEnableRequestSchema = {
    properties: {
        secret: {
            type: 'string',
            maxLength: 255,
            minLength: 16,
            title: 'Secret'
        },
        code: {
            type: 'string',
            maxLength: 6,
            minLength: 6,
            title: 'Code'
        }
    },
    type: 'object',
    required: ['secret', 'code'],
    title: 'MFAEnableRequest'
} as const;

export const MFASetupPublicSchema = {
    properties: {
        secret: {
            type: 'string',
            title: 'Secret'
        },
        otpauth_uri: {
            type: 'string',
            title: 'Otpauth Uri'
        }
    },
    type: 'object',
    required: ['secret', 'otpauth_uri'],
    title: 'MFASetupPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const TransactionBatchEnterSchema = {
    properties: {
        ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            minItems: 1,
            title: 'Ids'
        }
    },
    type: 'object',
    required: ['ids'],
    title: 'TransactionBatchEnter'
} as const;

export const TransactionCreateSchema = {
    properties: {
        category_id: {
            type: 'string',
            format: 'uuid',
            title: 'Category Id'
        },
        transaction_type: {
            '$ref': '#/components/schemas/TransactionType'
        },
        budget_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Budget Id'
        },
        summary: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        detail: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Detail'
        },
        entry_status: {
            '$ref': '#/components/schemas/EntryStatus'
        },
        handler_user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Handler User Id'
        },
        transaction_date: {
            type: 'string',
            format: 'date',
            title: 'Transaction Date'
        },
        amount: {
            type: 'number',
            exclusiveMinimum: 0,
            title: 'Amount'
        }
    },
    type: 'object',
    required: ['category_id', 'transaction_type', 'entry_status', 'transaction_date', 'amount'],
    title: 'TransactionCreate'
} as const;

export const TransactionPublicSchema = {
    properties: {
        category_id: {
            type: 'string',
            format: 'uuid',
            title: 'Category Id'
        },
        transaction_type: {
            '$ref': '#/components/schemas/TransactionType'
        },
        budget_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Budget Id'
        },
        summary: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        detail: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Detail'
        },
        entry_status: {
            '$ref': '#/components/schemas/EntryStatus'
        },
        handler_user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Handler User Id'
        },
        transaction_date: {
            type: 'string',
            format: 'date',
            title: 'Transaction Date'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        amount: {
            type: 'number',
            title: 'Amount'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        handler_display_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Handler Display Name'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['category_id', 'transaction_type', 'entry_status', 'transaction_date', 'id', 'amount', 'owner_id'],
    title: 'TransactionPublic'
} as const;

export const TransactionTypeSchema = {
    type: 'integer',
    enum: [1, 2],
    title: 'TransactionType'
} as const;

export const TransactionUpdateSchema = {
    properties: {
        category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        },
        transaction_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/TransactionType'
                },
                {
                    type: 'null'
                }
            ]
        },
        amount: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Amount'
        },
        budget_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Budget Id'
        },
        summary: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        detail: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Detail'
        },
        entry_status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/EntryStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        handler_user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Handler User Id'
        },
        transaction_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Transaction Date'
        }
    },
    type: 'object',
    title: 'TransactionUpdate'
} as const;

export const TransactionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TransactionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'TransactionsPublic'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        login_name: {
            type: 'string',
            maxLength: 100,
            title: 'Login Name'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'login_name', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        login_name: {
            type: 'string',
            maxLength: 100,
            title: 'Login Name'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        has_mfa: {
            type: 'boolean',
            title: 'Has Mfa',
            default: false
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'login_name', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        login_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Login Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        login_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Login Name'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        login_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Login Name'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;