// This file is auto-generated by @hey-api/openapi-ts

export type AdminResetPassword = {
    new_password: string;
};

export type AIConnectionPublic = {
    id: string;
    client_id: string;
    client_name: string;
    scopes: Array<(string)>;
    status: AIConnectionStatus;
    last_used_at?: (string | null);
    revoked_at?: (string | null);
    created_at: string;
};

export type AIConnectionsPublic = {
    data: Array<AIConnectionPublic>;
    count: number;
};

export type AIConnectionStatus = 'ACTIVE' | 'REVOKED' | 'REAUTH_REQUIRED';

export type Body_ai_connections_decide_authorization_request = {
    request: string;
    approved: boolean;
};

export type Body_data_jobs_create_import_job = {
    file: (Blob | File);
};

export type Body_login_login_access_token = {
    username: string;
    password: string;
    mfa_code?: (string | null);
};

export type BudgetCreate = {
    name: string;
    year: number;
    period: BudgetPeriod;
    amount: number;
};

export type BudgetPeriod = 1 | 2 | 3;

export type BudgetPublic = {
    name: string;
    year: number;
    period: BudgetPeriod;
    id: string;
    amount: number;
    used_amount?: number;
    owner_id: string;
    created_at?: (string | null);
};

export type BudgetsPublic = {
    data: Array<BudgetPublic>;
    count: number;
};

export type BudgetUpdate = {
    name?: (string | null);
    year?: (number | null);
    period?: (BudgetPeriod | null);
    amount?: (number | null);
};

export type CategoriesPublic = {
    data: Array<CategoryPublic>;
    count: number;
};

export type CategoryCreate = {
    name: string;
    parent_id?: (string | null);
    color: string;
};

export type CategoryPublic = {
    name: string;
    parent_id?: (string | null);
    color: string;
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type CategoryUpdate = {
    name?: (string | null);
    parent_id?: (string | null);
    color?: (string | null);
};

export type DashboardBudgetUsage = {
    budget_id: string;
    budget_name: string;
    amount: number;
    used_amount: number;
};

export type DashboardCategoryShare = {
    category_id: string;
    category_name: string;
    amount: number;
};

export type DashboardPublic = {
    summary: DashboardSummary;
    trends: Array<DashboardTrendPoint>;
    category_shares: Array<DashboardCategoryShare>;
    budget_usage: Array<DashboardBudgetUsage>;
};

export type DashboardSummary = {
    income: number;
    expense: number;
    balance: number;
};

export type DashboardTrendPoint = {
    month: string;
    income: number;
    expense: number;
};

export type DataJobPublic = {
    job_type: DataJobType;
    status?: DataJobStatus;
    template_version?: string;
    id: string;
    created_by: string;
    total_rows: number;
    success_rows: number;
    failed_rows: number;
    skipped_rows: number;
    progress_percent: number;
    failure_reason?: (string | null);
    started_at?: (string | null);
    finished_at?: (string | null);
    created_at?: (string | null);
    has_result_file?: boolean;
    has_error_file?: boolean;
};

export type DataJobsPublic = {
    data: Array<DataJobPublic>;
    count: number;
};

export type DataJobStatus = 'PENDING' | 'PROCESSING' | 'SUCCEEDED' | 'PARTIAL_SUCCESS' | 'FAILED' | 'CANCELLED';

export type DataJobType = 'EXPORT' | 'IMPORT';

export type EntryStatus = 1 | 2 | 3;

export type HandlerUserOption = {
    id: string;
    full_name?: (string | null);
    login_name: string;
    display_name: string;
};

export type HandlerUsersPublic = {
    data: Array<HandlerUserOption>;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LoginRequest = {
    login_name: string;
    password: string;
    mfa_code?: (string | null);
};

export type Message = {
    message: string;
};

export type MFAEnableRequest = {
    secret: string;
    code: string;
};

export type MFASetupPublic = {
    secret: string;
    otpauth_uri: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TransactionBatchEnter = {
    ids: Array<(string)>;
};

export type TransactionBatchEnterPublic = {
    updated_ids: Array<(string)>;
};

export type TransactionCreate = {
    category_id: string;
    transaction_type: TransactionType;
    budget_id?: (string | null);
    summary?: (string | null);
    description?: (string | null);
    detail?: ({
    [key: string]: unknown;
} | null);
    entry_status: EntryStatus;
    handler_user_id?: (string | null);
    transaction_date: string;
    amount: number;
};

export type TransactionPublic = {
    category_id: string;
    transaction_type: TransactionType;
    budget_id?: (string | null);
    summary?: (string | null);
    description?: (string | null);
    detail?: ({
    [key: string]: unknown;
} | null);
    entry_status: EntryStatus;
    handler_user_id?: (string | null);
    transaction_date: string;
    id: string;
    amount: number;
    owner_id: string;
    handler_display_name?: (string | null);
    created_at?: (string | null);
};

export type TransactionsPublic = {
    data: Array<TransactionPublic>;
    count: number;
};

export type TransactionType = 1 | 2;

export type TransactionUpdate = {
    category_id?: (string | null);
    transaction_type?: (TransactionType | null);
    amount?: (number | null);
    budget_id?: (string | null);
    summary?: (string | null);
    description?: (string | null);
    detail?: ({
    [key: string]: unknown;
} | null);
    entry_status?: (EntryStatus | null);
    handler_user_id?: (string | null);
    transaction_date?: (string | null);
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    login_name: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    login_name: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    has_mfa?: boolean;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    login_name?: (string | null);
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    login_name?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    login_name?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AiConnectionsListAiConnectionsData = {
    page?: number;
    pageSize?: number;
};

export type AiConnectionsListAiConnectionsResponse = (AIConnectionsPublic);

export type AiConnectionsReadAuthorizationRequestData = {
    request: string;
};

export type AiConnectionsReadAuthorizationRequestResponse = ({
    [key: string]: unknown;
});

export type AiConnectionsDecideAuthorizationRequestData = {
    requestBody: Body_ai_connections_decide_authorization_request;
};

export type AiConnectionsDecideAuthorizationRequestResponse = ({
    [key: string]: (string);
});

export type AiConnectionsRevokeAiConnectionData = {
    connectionId: string;
};

export type AiConnectionsRevokeAiConnectionResponse = (Message);

export type BudgetsReadBudgetsData = {
    limit?: number;
    page?: (number | null);
    pageSize?: (number | null);
    skip?: number;
};

export type BudgetsReadBudgetsResponse = (BudgetsPublic);

export type BudgetsCreateBudgetData = {
    requestBody: BudgetCreate;
};

export type BudgetsCreateBudgetResponse = (BudgetPublic);

export type BudgetsUpdateBudgetData = {
    budgetId: string;
    requestBody: BudgetUpdate;
};

export type BudgetsUpdateBudgetResponse = (BudgetPublic);

export type BudgetsDeleteBudgetData = {
    budgetId: string;
};

export type BudgetsDeleteBudgetResponse = (Message);

export type CategoriesReadCategoriesData = {
    limit?: number;
    page?: (number | null);
    pageSize?: (number | null);
    skip?: number;
};

export type CategoriesReadCategoriesResponse = (CategoriesPublic);

export type CategoriesCreateCategoryData = {
    requestBody: CategoryCreate;
};

export type CategoriesCreateCategoryResponse = (CategoryPublic);

export type CategoriesUpdateCategoryData = {
    categoryId: string;
    requestBody: CategoryUpdate;
};

export type CategoriesUpdateCategoryResponse = (CategoryPublic);

export type CategoriesDeleteCategoryData = {
    categoryId: string;
};

export type CategoriesDeleteCategoryResponse = (Message);

export type DashboardReadDashboardResponse = (DashboardPublic);

export type DataJobsReadDataJobsData = {
    limit?: number;
    page?: (number | null);
    pageSize?: (number | null);
    skip?: number;
};

export type DataJobsReadDataJobsResponse = (DataJobsPublic);

export type DataJobsCreateExportJobResponse = (DataJobPublic);

export type DataJobsCreateImportJobData = {
    formData: Body_data_jobs_create_import_job;
};

export type DataJobsCreateImportJobResponse = (DataJobPublic);

export type DataJobsDownloadTemplateResponse = ((Blob | File));

export type DataJobsDownloadResultFileData = {
    jobId: string;
};

export type DataJobsDownloadResultFileResponse = ((Blob | File));

export type DataJobsDownloadErrorFileData = {
    jobId: string;
};

export type DataJobsDownloadErrorFileResponse = ((Blob | File));

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginLoginData = {
    requestBody: LoginRequest;
};

export type LoginLoginResponse = (UserPublic);

export type LoginLogoutResponse = (unknown);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type TransactionsReadTransactionsData = {
    categoryId?: (string | null);
    endDate?: (string | null);
    entryStatus?: (EntryStatus | null);
    handlerUserId?: (string | null);
    limit?: number;
    page?: (number | null);
    pageSize?: (number | null);
    skip?: number;
    startDate?: (string | null);
    transactionType?: (TransactionType | null);
};

export type TransactionsReadTransactionsResponse = (TransactionsPublic);

export type TransactionsCreateTransactionData = {
    requestBody: TransactionCreate;
};

export type TransactionsCreateTransactionResponse = (TransactionPublic);

export type TransactionsReadTransactionData = {
    transactionId: string;
};

export type TransactionsReadTransactionResponse = (TransactionPublic);

export type TransactionsUpdateTransactionData = {
    requestBody: TransactionUpdate;
    transactionId: string;
};

export type TransactionsUpdateTransactionResponse = (TransactionPublic);

export type TransactionsDeleteTransactionData = {
    transactionId: string;
};

export type TransactionsDeleteTransactionResponse = (Message);

export type TransactionsBatchEnterTransactionsData = {
    requestBody: TransactionBatchEnter;
};

export type TransactionsBatchEnterTransactionsResponse = (TransactionBatchEnterPublic);

export type UsersReadUsersData = {
    limit?: number;
    page?: (number | null);
    pageSize?: (number | null);
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadHandlerOptionsData = {
    limit?: number;
    page?: (number | null);
    pageSize?: (number | null);
    skip?: number;
};

export type UsersReadHandlerOptionsResponse = (HandlerUsersPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersSetupMfaResponse = (MFASetupPublic);

export type UsersEnableMfaData = {
    requestBody: MFAEnableRequest;
};

export type UsersEnableMfaResponse = (Message);

export type UsersResetMyMfaResponse = (Message);

export type UsersDisableMyMfaResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UsersResetUserPasswordData = {
    requestBody: AdminResetPassword;
    userId: string;
};

export type UsersResetUserPasswordResponse = (Message);

export type UsersResetUserMfaData = {
    userId: string;
};

export type UsersResetUserMfaResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);