/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutBudgetsRouteImport } from './routes/_layout/budgets'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutTransactionsRouteImport } from './routes/_layout/transactions'
import { Route as LayoutConnectAuthorizeRouteImport } from './routes/_layout/connect.authorize'
import { Route as LayoutSystemAccountsRouteImport } from './routes/_layout/system.accounts'
import { Route as LayoutSystemCategoriesRouteImport } from './routes/_layout/system.categories'
import { Route as LayoutSystemDataManagementRouteImport } from './routes/_layout/system.data-management'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBudgetsRoute = LayoutBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTransactionsRoute = LayoutTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConnectAuthorizeRoute = LayoutConnectAuthorizeRouteImport.update({
  id: '/connect/authorize',
  path: '/connect/authorize',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemAccountsRoute = LayoutSystemAccountsRouteImport.update({
  id: '/system/accounts',
  path: '/system/accounts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemCategoriesRoute = LayoutSystemCategoriesRouteImport.update({
  id: '/system/categories',
  path: '/system/categories',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemDataManagementRoute =
  LayoutSystemDataManagementRouteImport.update({
    id: '/system/data-management',
    path: '/system/data-management',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/budgets': typeof LayoutBudgetsRoute
  '/settings': typeof LayoutSettingsRoute
  '/transactions': typeof LayoutTransactionsRoute
  '/connect/authorize': typeof LayoutConnectAuthorizeRoute
  '/system/accounts': typeof LayoutSystemAccountsRoute
  '/system/categories': typeof LayoutSystemCategoriesRoute
  '/system/data-management': typeof LayoutSystemDataManagementRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/budgets': typeof LayoutBudgetsRoute
  '/settings': typeof LayoutSettingsRoute
  '/transactions': typeof LayoutTransactionsRoute
  '/': typeof LayoutIndexRoute
  '/connect/authorize': typeof LayoutConnectAuthorizeRoute
  '/system/accounts': typeof LayoutSystemAccountsRoute
  '/system/categories': typeof LayoutSystemCategoriesRoute
  '/system/data-management': typeof LayoutSystemDataManagementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/budgets': typeof LayoutBudgetsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/transactions': typeof LayoutTransactionsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/connect/authorize': typeof LayoutConnectAuthorizeRoute
  '/_layout/system/accounts': typeof LayoutSystemAccountsRoute
  '/_layout/system/categories': typeof LayoutSystemCategoriesRoute
  '/_layout/system/data-management': typeof LayoutSystemDataManagementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/budgets'
    | '/settings'
    | '/transactions'
    | '/connect/authorize'
    | '/system/accounts'
    | '/system/categories'
    | '/system/data-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/budgets'
    | '/settings'
    | '/transactions'
    | '/'
    | '/connect/authorize'
    | '/system/accounts'
    | '/system/categories'
    | '/system/data-management'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/budgets'
    | '/_layout/settings'
    | '/_layout/transactions'
    | '/_layout/'
    | '/_layout/connect/authorize'
    | '/_layout/system/accounts'
    | '/_layout/system/categories'
    | '/_layout/system/data-management'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/budgets': {
      id: '/_layout/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof LayoutBudgetsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/transactions': {
      id: '/_layout/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof LayoutTransactionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/connect/authorize': {
      id: '/_layout/connect/authorize'
      path: '/connect/authorize'
      fullPath: '/connect/authorize'
      preLoaderRoute: typeof LayoutConnectAuthorizeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/accounts': {
      id: '/_layout/system/accounts'
      path: '/system/accounts'
      fullPath: '/system/accounts'
      preLoaderRoute: typeof LayoutSystemAccountsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/categories': {
      id: '/_layout/system/categories'
      path: '/system/categories'
      fullPath: '/system/categories'
      preLoaderRoute: typeof LayoutSystemCategoriesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/data-management': {
      id: '/_layout/system/data-management'
      path: '/system/data-management'
      fullPath: '/system/data-management'
      preLoaderRoute: typeof LayoutSystemDataManagementRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutBudgetsRoute: typeof LayoutBudgetsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTransactionsRoute: typeof LayoutTransactionsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutConnectAuthorizeRoute: typeof LayoutConnectAuthorizeRoute
  LayoutSystemAccountsRoute: typeof LayoutSystemAccountsRoute
  LayoutSystemCategoriesRoute: typeof LayoutSystemCategoriesRoute
  LayoutSystemDataManagementRoute: typeof LayoutSystemDataManagementRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutBudgetsRoute: LayoutBudgetsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTransactionsRoute: LayoutTransactionsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutConnectAuthorizeRoute: LayoutConnectAuthorizeRoute,
  LayoutSystemAccountsRoute: LayoutSystemAccountsRoute,
  LayoutSystemCategoriesRoute: LayoutSystemCategoriesRoute,
  LayoutSystemDataManagementRoute: LayoutSystemDataManagementRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
