name: Test Docker Compose

on:
  workflow_dispatch:

permissions: {}

jobs:

  test-docker-compose:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - run: docker compose --profile adminer build
      - run: docker compose down -v --remove-orphans
      - run: docker compose --profile adminer up -d --wait backend frontend adminer
      - name: Test backend is up
        run: curl http://127.0.0.1:21001/api/v1/utils/health-check
      - name: Test frontend is up
        run: curl http://127.0.0.1:21000
      - run: docker compose down -v --remove-orphans
